MSG_TYPE_RESULT = 'result'

MSG_TYPE_COMMAND = 'command'
MSG_TYPE_SCRIPT = 'script'
MSG_TYPE_ACMD = 'acmd'

MSG_TYPE_CANCEL = 'cancel'
MSG_TYPE_CANCEL_ACK = 'cancel_ack'

MSG_TYPE_HEARTBEAT = 'heartbeat'
MSG_TYPE_HEARTBEAT_ACK = 'heartbeat_ack'
MSG_TYPE_PTY_OPEN = 'pty_open'
MSG_TYPE_PTY_INPUT = 'pty_input'
MSG_TYPE_PTY_RESIZE = 'pty_resize'
MSG_TYPE_PTY_CLOSE = 'pty_close'
MSG_TYPE_PTY_OPENED = 'pty_opened'
MSG_TYPE_PTY_OUTPUT = 'pty_output'
MSG_TYPE_PTY_CLOSED = 'pty_closed'
MSG_TYPE_PTY_ERROR = 'pty_error'

MSG_TYPE_SCREEN_OPEN = 'screen_open'
MSG_TYPE_SCREEN_CONFIG = 'screen_config'
MSG_TYPE_SCREEN_CLOSE = 'screen_close'
MSG_TYPE_SCREEN_INPUT = 'screen_input'
MSG_TYPE_SCREEN_OPENED = 'screen_opened'
MSG_TYPE_SCREEN_FRAME = 'screen_frame'
MSG_TYPE_SCREEN_CLOSED = 'screen_closed'
MSG_TYPE_SCREEN_ERROR = 'screen_error'
MSG_TYPE_SCREEN_INPUT_ERROR = 'screen_input_error'
MSG_TYPE_CLIPBOARD_GET = 'clipboard_get'
MSG_TYPE_CLIPBOARD_SET = 'clipboard_set'
MSG_TYPE_CLIPBOARD_RESULT = 'clipboard_result'

MSG_TYPE_MONITOR_OPEN = 'monitor_open'
MSG_TYPE_MONITOR_CONFIG = 'monitor_config'
MSG_TYPE_MONITOR_CLOSE = 'monitor_close'
MSG_TYPE_MONITOR_OPENED = 'monitor_opened'
MSG_TYPE_MONITOR_SNAPSHOT = 'monitor_snapshot'
MSG_TYPE_MONITOR_ERROR = 'monitor_error'
MSG_TYPE_MONITOR_CLOSED = 'monitor_closed'


MSG_TYPE_TRANSFER_START = 'transfer_start'
MSG_TYPE_TRANSFER_CANCEL = 'transfer_cancel'
MSG_TYPE_TRANSFER_UPDATE = 'transfer_update'
