from server.config.config import WEB_FILE_TRANSFER_PORT


class AgentBootstrapScriptService:
    """
    Agent bootstrap 脚本生成服务。

    职责：
    - 校验并归一化 bootstrap 请求参数
    - 生成跨平台 Python bootstrap 脚本
    - 生成 Windows PowerShell bootstrap 脚本
    """

    def normalize_bootstrap_payload(self, payload: dict) -> dict:
        if not isinstance(payload, dict):
            raise ValueError('Invalid bootstrap payload')

        server_host = (payload.get('server_host') or '').strip()
        server_port = payload.get('server_port')
        web_port = payload.get('web_port')
        file_transfer_port = payload.get('file_transfer_port') or WEB_FILE_TRANSFER_PORT
        web_host = (payload.get('web_host') or server_host).strip() or server_host
        web_scheme = (payload.get('web_scheme') or 'http').strip() or 'http'

        if not server_host:
            raise ValueError('server_host is required')
        if not server_port:
            raise ValueError('server_port is required')
        if not web_port:
            raise ValueError('web_port is required')

        try:
            server_port = int(server_port)
        except (ValueError, TypeError):
            raise ValueError('server_port must be integer')

        try:
            web_port = int(web_port)
        except (ValueError, TypeError):
            raise ValueError('web_port must be integer')

        try:
            file_transfer_port = int(file_transfer_port)
        except (ValueError, TypeError):
            raise ValueError('file_transfer_port must be integer')

        return {
            'server_host': server_host,
            'server_port': server_port,
            'web_host': web_host,
            'web_port': web_port,
            'file_transfer_port': file_transfer_port,
            'web_scheme': web_scheme,
        }

    def generate_python_script(self, payload: dict) -> str:
        params = self.normalize_bootstrap_payload(payload)
        return self._generate_python_script(
            params['server_host'],
            params['server_port'],
            params['web_host'],
            params['web_port'],
            params['file_transfer_port'],
            params['web_scheme'],
        )

    def generate_powershell_script(self, payload: dict) -> str:
        params = self.normalize_bootstrap_payload(payload)
        return self._generate_powershell_script(
            params['server_host'],
            params['server_port'],
            params['web_port'],
            params['file_transfer_port'],
        )

    def _generate_python_script(self, server_host, server_port, web_host, web_port, file_transfer_port, web_scheme='http'):
        script = f'''# bootstrap.py - Cross-platform bootstrap script
# Generated by server API
import os, sys, time, shutil, zipfile, runpy, threading, json, platform, subprocess
from urllib.parse import urljoin
import requests

WEB_HOST = "{web_host}"
WEB_PORT = {web_port}
FILE_TRANSFER_PORT = {file_transfer_port}
WEB_SCHEME = "{web_scheme}"
SERVER_HOST = "{server_host}"
SERVER_PORT = {server_port}

BASE_URL = f"{{WEB_SCHEME}}://{{WEB_HOST}}:{{WEB_PORT}}"
RELEASE_DIR = os.path.join(os.path.expanduser("~"), "Documents", "client_bundle", "releases")

def log(msg):
    print(f"[bootstrap] {{msg}}")

def ensure_dir(path):
    os.makedirs(path, exist_ok=True)
    return path

def is_pythonista():
    try:
        import appex
        return True
    except ImportError:
        return sys.platform == 'ios'

def build_bundle():
    url = urljoin(BASE_URL + "/", "/api/agent/build")
    payload = {{
        "server_host": SERVER_HOST,
        "server_port": SERVER_PORT,
        "server_web_scheme": WEB_SCHEME,
        "server_web_host": WEB_HOST,
        "web_port": WEB_PORT,
        "file_transfer_port": FILE_TRANSFER_PORT,
        "target_os": "bundle",
        "builder": "bundle",
        "target_arch": "",
        "source": "bootstrap",
    }}
    log(f"build request: {{url}}")
    r = requests.post(url, json=payload, timeout=300)
    r.raise_for_status()
    data = r.json()
    if isinstance(data, dict) and "code" in data:
        if data.get("code") != 0:
            raise RuntimeError(data.get("message") or data)
        return data.get("data") or {{}}
    return data

def download_file(download_url, save_path):
    log(f"download: {{download_url}}")
    r = requests.get(download_url, stream=True, timeout=300)
    r.raise_for_status()
    tmp_path = save_path + ".part"
    with open(tmp_path, "wb") as f:
        for chunk in r.iter_content(chunk_size=1024 * 64):
            if chunk:
                f.write(chunk)
    if os.path.exists(save_path):
        os.remove(save_path)
    os.rename(tmp_path, save_path)
    return save_path

def unzip(zip_path, extract_dir):
    if os.path.isdir(extract_dir):
        shutil.rmtree(extract_dir)
    os.makedirs(extract_dir, exist_ok=True)
    log(f"extract: {{extract_dir}}")
    with zipfile.ZipFile(zip_path, "r") as z:
        z.extractall(extract_dir)
    return extract_dir

def start_rchclient(bundle_dir):
    rchclient_path = os.path.join(bundle_dir, "rchclient.py")
    if not os.path.isfile(rchclient_path):
        raise FileNotFoundError(f"rchclient.py not found: {{rchclient_path}}")

    if is_pythonista():
        log("iOS/Pythonista detected, using runpy mode")
        def runner():
            os.chdir(bundle_dir)
            if bundle_dir not in sys.path:
                sys.path.insert(0, bundle_dir)
            sys.argv = [rchclient_path]
            runpy.run_path(rchclient_path, run_name="__main__")
        t = threading.Thread(target=runner, name="rchclient-main")
        t.daemon = False
        t.start()
        return t
    else:
        log(f"Desktop detected ({{sys.platform}}), using subprocess detached mode")
        cmd = [sys.executable, rchclient_path]
        if sys.platform == 'win32':
            flags = 0x00000200 | 0x00000008
            return subprocess.Popen(
                cmd, cwd=bundle_dir,
                stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
                stdin=subprocess.DEVNULL,
                creationflags=flags, close_fds=True
            )
        else:
            return subprocess.Popen(
                cmd, cwd=bundle_dir,
                stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
                stdin=subprocess.DEVNULL,
                start_new_session=True, close_fds=True
            )

def main():
    ensure_dir(RELEASE_DIR)
    result = build_bundle()
    download_url = result.get("download_url")
    if not download_url:
        raise RuntimeError(f"missing download_url: {{result}}")
    download_url = urljoin(BASE_URL + "/", download_url)
    file_name = result.get("file_name") or os.path.basename(download_url)
    zip_path = os.path.join(RELEASE_DIR, file_name)
    base_name = os.path.splitext(file_name)[0]
    extract_dir = os.path.join(RELEASE_DIR, base_name)
    download_file(download_url, zip_path)
    unzip(zip_path, extract_dir)
    start_rchclient(extract_dir)
    log("handoff done, bootstrap exits")
    time.sleep(0.2)
    sys.exit(0)

if __name__ == "__main__":
    main()
'''
        return script

    def _generate_powershell_script(self, server_host, server_port, web_port, file_transfer_port):
        script = f'''$ip="{server_host}"
$webPort={web_port}
$fileTransferPort={file_transfer_port}
$serverPort={server_port}
$bundleDir="$env:USERPROFILE\\client_bundle"
$pyDir="$bundleDir\\python-embed"
$releaseDir="$bundleDir\\releases"
mkdir $bundleDir,$releaseDir -Force | Out-Null

function Unzip-File($zipPath, $destPath) {{
    mkdir $destPath -Force | Out-Null
    Add-Type -AssemblyName System.IO.Compression.FileSystem
    [System.IO.Compression.ZipFile]::ExtractToDirectory($zipPath, $destPath)
}}

# 1. Prepare Python
$py = $null
if (Get-Command python -ErrorAction SilentlyContinue) {{
    $py = "python"
    Write-Host "Found local Python: $py"
}} elseif (Get-Command python3 -ErrorAction SilentlyContinue) {{
    $py = "python3"
    Write-Host "Found local Python: $py"
}}

if (-not $py) {{
    if (Test-Path "$pyDir\\python.exe") {{
        $py = "$pyDir\\python.exe"
        Write-Host "Using cached embedded Python: $py"
    }} else {{
        $found = Get-ChildItem $pyDir -Filter "python.exe" -Recurse -ErrorAction SilentlyContinue | Select-Object -First 1
        if ($found) {{
            $py = $found.FullName
            Write-Host "Using cached embedded Python: $py"
        }}
    }}
}}

if (-not $py) {{
    Write-Host "No Python found, downloading embedded Python..."
    $pyZip = "$bundleDir\\python-embed.zip"
    mkdir $pyDir -Force | Out-Null
    iwr "http://$ip`:$webPort/api/external-tools/python-embed/download?platform=win&arch=amd64" -OutFile $pyZip -UseBasicParsing
    if (-not (Test-Path $pyZip)) {{
        Write-Host "ERROR: Download failed"
        exit 1
    }}
    Write-Host "Downloaded, extracting..."
    Unzip-File $pyZip $pyDir
    $py = Get-ChildItem $pyDir -Filter "python.exe" -Recurse | Select-Object -First 1 -ExpandProperty FullName
    if (-not $py) {{
        Write-Host "ERROR: python.exe not found after extraction"
        exit 1
    }}
    Remove-Item $pyZip -Force
    Write-Host "Embedded Python ready: $py"
}}

# 2. Request bundle build
Write-Host "Requesting bundle build..."
$buildBody = "{{`"server_host`":`"$ip`",`"server_port`":$serverPort,`"web_port`":$webPort,`"file_transfer_port`":$fileTransferPort,`"target_os`":`"bundle`",`"builder`":`"bundle`",`"target_arch`":`"`",`"source`":`"bootstrap`",`"server_web_scheme`":`"http`",`"server_web_host`":`"$ip`"}}"
$buildResp = iwr "http://$ip`:$webPort/api/agent/build" -Method Post -ContentType "application/json" -UseBasicParsing -Body $buildBody
$buildData = $buildResp.Content | ConvertFrom-Json

if ($buildData.code -ne 0) {{
    Write-Host "Build failed: $($buildData.message)"
    exit 1
}}

$downloadUrl = $buildData.data.download_url
$fileName = $buildData.data.file_name
$buildVersion = $buildData.data.build_version

if (-not $downloadUrl.StartsWith("http")) {{
    $downloadUrl = "http://$ip`:$webPort$downloadUrl"
}}

Write-Host "Build version: $buildVersion"

# 3. Download bundle (always download latest)
$zipPath = "$releaseDir\\$fileName"
Write-Host "Downloading bundle..."
iwr $downloadUrl -OutFile $zipPath -UseBasicParsing
if (-not (Test-Path $zipPath)) {{
    Write-Host "ERROR: Bundle download failed"
    exit 1
}}

# 4. Extract (skip if already extracted)
$extractDir = "$releaseDir\\$buildVersion"
$rchclient = "$extractDir\\rchclient.py"
if (Test-Path $rchclient) {{
    Write-Host "Bundle already extracted, skipping..."
}} else {{
    Write-Host "Extracting to $extractDir..."
    Unzip-File $zipPath $extractDir
}}

# 5. Launch rchclient
if (-not (Test-Path $rchclient)) {{
    Write-Host "ERROR: rchclient.py not found: $rchclient"
    exit 1
}}

Write-Host "Launching rchclient..."
Start-Process -FilePath $py -ArgumentList $rchclient -WorkingDirectory $extractDir -WindowStyle Hidden
Write-Host "Bootstrap complete."
'''
        return script
